[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dynamic-rescheduling-logistics"
version = "0.1.0"
dependencies = ["ortools>=9.14"]

[tool.setuptools.packages.find]
where = ["src"]
